// State
let orders = [];
let availableInvoices = []; // Invoices loaded from API
let currentUser = null;
let currentUserId = null;
let currentUserRole = null; // 'ADMIN', 'DISPATCH', 'DRIVER', or 'REPORTS_ONLY'
let accessToken = getToken() || null;     // JWT token, restored from localStorage on page load
let loginIntent = null; // 'manifest' or 'report'
let currentReportView = 'dispatched'; // 'dispatched' or 'outstanding'

// Role constants
const ROLE_ADMIN        = 'ADMIN';
const ROLE_DISPATCH     = 'DISPATCH';
const ROLE_REPORTS_ONLY = 'REPORTS_ONLY';

// API Configuration
// Use relative paths so fetch() calls work on any host/port (local or Render production).
const API_URL = '/api';

// Safety check: Log resolved origin on startup
console.log(`[API Config] Using relative API paths. Page origin: ${window.location.origin}`);

// apiFetch is provided by auth.js (loaded before this script)

// Error Logger for UI
function logError(msg) {
    console.error(msg);
    let errBox = document.getElementById('debug-error-box');
    if (!errBox) {
        errBox = document.createElement('div');
        errBox.id = 'debug-error-box';
        errBox.style = "position:fixed; bottom:10px; right:10px; background:red; color:white; padding:10px; z-index:99999; max-width:300px; border-radius:5px; font-family:sans-serif; font-size:12px;";
        document.body.appendChild(errBox);
    }
    errBox.innerText = "Error: " + msg;
}

// Global Error Handler to catch unexpected crashes
window.onerror = function (msg, url, lineNo, columnNo, error) {
    logError(`System Error: ${msg} (Line ${lineNo})`);
    return false;
};

// Manifest Number — generated by backend on save.
// Placeholder shown before manifest is finalised.
const MANIFEST_PLACEHOLDER = 'Assigned on save';

// Maps username → user id; populated at load time for ADMIN role only.
// Used to attach assignment IDs to the save-report payload.
let usernameToIdMap = {};

// Settings Data Structure
let settingsData = {
    drivers: [],
    assistants: [],
    checkers: [],
    routes: [],
    trucks: [], // Each truck: { reg, driver, assistant, checker }
    customerRoutes: [] // [{ customer_name, route_name, delivery_mode }, ...]
};

// Load settings from API
async function loadSettings() {
    // Fetches one endpoint and returns parsed JSON, or null on any failure.
    // Never throws — all errors are logged to console only.
    async function safeFetch(url, label) {
        try {
            const res = await apiFetch(url);
            if (!res.ok) {
                console.error(`[Settings] ${label} returned HTTP ${res.status} ${res.statusText}`);
                return null;
            }
            return await res.json();
        } catch (err) {
            console.error(`[Settings] ${label} request failed: ${err.message}`);
            return null;
        }
    }

    const [driversData, assistantsData, checkersData, routesData, trucksData, custRoutesData] =
        await Promise.all([
            safeFetch(`${API_URL}/settings/drivers`,    'Drivers'),
            safeFetch(`${API_URL}/settings/assistants`, 'Assistants'),
            safeFetch(`${API_URL}/settings/checkers`,   'Checkers'),
            safeFetch(`${API_URL}/settings/routes`,     'Routes'),
            safeFetch(`${API_URL}/trucks`,              'Trucks'),
            safeFetch(`${API_URL}/customer-routes`,     'Customer Routes'),
        ]);

    // Safely apply data — null-safe, falls back to empty collections
    settingsData.drivers        = driversData?.values    ?? [];
    settingsData.assistants     = assistantsData?.values ?? [];
    settingsData.checkers       = checkersData?.values   ?? [];
    settingsData.routes         = routesData?.values     ?? [];
    settingsData.trucks         = trucksData?.trucks     ?? [];
    settingsData.customerRoutes = custRoutesData?.routes ?? [];

    // Only alert the user if every single endpoint failed (server unreachable)
    const allFailed = [driversData, assistantsData, checkersData, routesData, trucksData, custRoutesData]
        .every(d => d === null);

    if (allFailed) {
        console.error('[Settings] All endpoints unreachable — backend may not be running.');
        logError('Connection Failed: Backend unreachable. Please try again later.');
    } else {
        console.log('[Settings] Settings loaded from server.');
    }

    // Refresh UI list renders if the settings panel is available
    if (typeof renderSettingsList === 'function') {
        try {
            renderSettingsList('drivers');
            renderSettingsList('assistants');
            renderSettingsList('checkers');
            renderSettingsList('routes');
            renderTrucksList();
        } catch (e) {
            console.warn('[Settings] UI refresh failed:', e);
        }
    }

    // ADMIN only: build username → user id map so assignment IDs can be
    // included in the save-report payload without requiring a separate lookup.
    // DISPATCH users cannot call GET /api/users; the backend resolves IDs
    // from text names via username lookup for those sessions.
    if (currentUserRole === ROLE_ADMIN) {
        try {
            const usersRes = await apiFetch(`${API_URL}/users`);
            if (usersRes.ok) {
                const usersData = await usersRes.json();
                usernameToIdMap = {};
                (usersData.users || []).forEach(u => {
                    if (u.username && u.id) {
                        usernameToIdMap[u.username] = u.id;
                    }
                });
                console.log(`[Settings] Loaded ${Object.keys(usernameToIdMap).length} user ID mapping(s) for assignment resolution.`);
            }
        } catch (err) {
            console.warn('[Settings] User ID map load failed (non-fatal):', err.message);
        }
    }
}


// DOM Elements
const formInputs = {
    manifestNumber: document.getElementById('manifest-number'),
    date: document.getElementById('date'),
    regNumber: document.getElementById('reg-number'),
    driver: document.getElementById('driver'),
    assistant: document.getElementById('assistant'),
    checker: document.getElementById('checker'),
    palletsBrown: document.getElementById('pallets-brown'),
    palletsBlue: document.getElementById('pallets-blue'),
    crates: document.getElementById('crates'),
    mileage: document.getElementById('mileage'),
    deliveryType: document.getElementById('delivery-type'),
    thirdPartyProvider: document.getElementById('third-party-provider'),
    consignmentNumber: document.getElementById('consignment-number'),
    consignmentDate: document.getElementById('consignment-date'),
    consignmentNotes: document.getElementById('consignment-notes'),
};

const orderInputs = {
    invoice: document.getElementById('invoice-number'),
    orderNumber: document.getElementById('order-number-manual'),
    invoiceDate: document.getElementById('invoice-date-manual'),
    customer: document.getElementById('customer-name'),
    area: document.getElementById('order-area'),
    sku: document.getElementById('sku'),
    value: document.getElementById('order-value'),
    weight: document.getElementById('weight'),
};

const tableBody = document.querySelector('#manifest-table tbody');
const totalSkuEl = document.getElementById('total-sku');
const totalValueEl = document.getElementById('total-value');
const totalWeightEl = document.getElementById('total-weight');
const orderCountEl = document.getElementById('order-count');

// Initialization
document.addEventListener('DOMContentLoaded', async () => {
    // Non-API setup — safe to run regardless of auth state
    setDefaultDate();
    setupEventListeners();

    // Compute auth state once.  Both token AND stored username must be present —
    // a stale username or expired-token string alone is not a valid session.
    if (getToken() && localStorage.getItem('currentUser')) {
        // ── Branch A: authenticated ────────────────────────────────────────
        // All protected dashboard API calls happen here and nowhere else on
        // startup.  No protected calls run in the unauthenticated branch.
        try {
            await loadSettings();
        } catch (e) {
            console.warn("Settings failed to load, continuing with empty defaults");
            logError("Settings failed, continuing with empty defaults");
        }
        await loadState();
        initManifestNumber();
        initTruckDropdown();
        initPersonnelDropdowns();
        await renderTable();
        if (formInputs.regNumber.value) {
            handleTruckChange();
        }
        restoreSessionUI();
    } else {
        // ── Branch B: unauthenticated ──────────────────────────────────────
        // Show login.  No dashboard API calls are made.
        showLandingPage();
    }

    // Auth decision is resolved — reveal the app shell (was hidden during
    // auth-pending to prevent dashboard HTML from flashing before JS runs).
    document.body.classList.remove('auth-pending');

    // Initialize DEV_MODE if available
    if (window.DevMode) {
        window.DevMode.init();
    }
});

/**
 * pageshow fires on every page display, including bfcache restores.
 * When event.persisted is true the browser returned this page from its
 * back-forward cache: DOMContentLoaded did NOT re-fire, so we must
 * re-check auth state here to keep the landing overlay in sync.
 *
 * We only toggle the overlay and reset permissions — we deliberately
 * do NOT re-run loadSettings() / renderTable() to avoid unnecessary
 * API calls and UI flicker on a bfcache hit.
 */
window.addEventListener('pageshow', (event) => {
    if (!event.persisted) return; // Normal load — DOMContentLoaded already handled it.

    if (getToken() && localStorage.getItem('currentUser')) {
        // Session is still alive after navigating back — restore the dashboard.
        restoreSessionUI();
    } else {
        // Session was cleared (e.g. 401 on another page) — show login.
        showLandingPage();
    }
});

// Initialize manifest number placeholder (actual number assigned by backend on save)
function initManifestNumber() {
    if (!formInputs.manifestNumber.value || formInputs.manifestNumber.value === MANIFEST_PLACEHOLDER) {
        formInputs.manifestNumber.value = MANIFEST_PLACEHOLDER;
    }
}

function initTruckDropdown() {
    const select = formInputs.regNumber;
    // Clear existing options except the first one (if any) or just rebuild
    select.innerHTML = '<option value="">Select Truck</option>';

    settingsData.trucks.forEach(truck => {
        const option = document.createElement('option');
        option.value = truck.reg;
        option.textContent = truck.reg;
        select.appendChild(option);
    });
}

// Initialize Driver, Assistant, Checker dropdowns with values from settings
function initPersonnelDropdowns() {
    // Get personnel from settings
    const drivers = settingsData.drivers || [];
    const assistants = settingsData.assistants || [];
    const checkers = settingsData.checkers || [];

    // console.log("Initializing Dropdowns:", { drivers, assistants, checkers });

    // Populate Driver dropdown
    const driverSelect = formInputs.driver;
    const currentDriver = driverSelect.value; // Store current selection
    driverSelect.innerHTML = '<option value="">Select Driver</option>';
    drivers.forEach(name => {
        const option = document.createElement('option');
        option.value = name;
        option.textContent = name;
        const uid = usernameToIdMap[name];
        if (uid) option.dataset.userId = uid;
        if (name === currentDriver) option.selected = true;
        driverSelect.appendChild(option);
    });

    // Populate Assistant dropdown
    const assistantSelect = formInputs.assistant;
    const currentAssistant = assistantSelect.value;
    assistantSelect.innerHTML = '<option value="">Select Assistant</option>';
    assistants.forEach(name => {
        const option = document.createElement('option');
        option.value = name;
        option.textContent = name;
        const uid = usernameToIdMap[name];
        if (uid) option.dataset.userId = uid;
        if (name === currentAssistant) option.selected = true;
        assistantSelect.appendChild(option);
    });

    // Populate Checker dropdown
    const checkerSelect = formInputs.checker;
    const currentChecker = checkerSelect.value;
    checkerSelect.innerHTML = '<option value="">Select Checker</option>';
    checkers.forEach(name => {
        const option = document.createElement('option');
        option.value = name;
        option.textContent = name;
        if (name === currentChecker) option.selected = true;
        checkerSelect.appendChild(option);
    });
}

function handleTruckChange() {
    const selectedReg = formInputs.regNumber.value;
    const truck = settingsData.trucks.find(t => t.reg === selectedReg);

    if (truck) {
        formInputs.driver.value = truck.driver;
        formInputs.assistant.value = truck.assistant;
        formInputs.checker.value = truck.checker;
        saveState(); // Save auto-filled values
    } else if (selectedReg === "") {
        // Optional: clear fields if "Select Truck" is chosen?
        // formInputs.driver.value = "";
        // formInputs.assistant.value = "";
        // formInputs.checker.value = "";
    }
}

function setupEventListeners() {
    try {
        document.getElementById('add-order-btn').addEventListener('click', addOrder);
        document.getElementById('reset-btn').addEventListener('click', resetSystem);
        document.getElementById('print-btn').addEventListener('click', showPreviewModal);
        document.getElementById('view-reports-btn').addEventListener('click', showReports);
        document.getElementById('close-modal-btn').addEventListener('click', hideReports);
        document.getElementById('filter-btn').addEventListener('click', filterReports);
        document.getElementById('export-report-btn').addEventListener('click', showExportOptions);
        // document.getElementById('clear-history-btn').addEventListener('click', clearReportHistory);
        document.getElementById('logout-btn').addEventListener('click', handleLogout);

        // New navigation buttons
        document.getElementById('analytics-btn').addEventListener('click', () => {
            window.location.href = 'analytics.html';
        });
        document.getElementById('dispatch-report-btn').addEventListener('click', () => {
            window.location.href = 'dispatch_report.html';
        });
        document.getElementById('outstanding-orders-btn').addEventListener('click', () => {
            window.location.href = 'outstanding_orders.html';
        });

        // Call secondary listeners
        initSecondaryListeners();
    } catch (error) {
        console.error("Error in setupEventListeners:", error);
        // Try to continue with secondary listeners even if primary setup fails
        try {
            initSecondaryListeners();
        } catch (e) {
            console.error("Error in initSecondaryListeners:", e);
        }
    }
}

// ... (previous functions) ...

function initSecondaryListeners() {
    // Export Options listeners
    document.getElementById('close-export-options-btn').addEventListener('click', hideExportOptions);
    document.getElementById('export-download-btn').addEventListener('click', () => {
        hideExportOptions();
        exportDispatchReport();
    });
    document.getElementById('export-print-preview-btn').addEventListener('click', showReportPrintPreview);

    // Print Preview listeners
    document.getElementById('close-report-preview-btn').addEventListener('click', hideReportPreview);
    document.getElementById('cancel-report-print-btn').addEventListener('click', hideReportPreview);
    document.getElementById('confirm-report-print-btn').addEventListener('click', () => window.print());

    // Search filter listeners
    document.getElementById('report-search').addEventListener('input', handleSearchInput);
    document.getElementById('clear-search-btn').addEventListener('click', clearSearch);

    // View toggle listeners
    document.getElementById('view-dispatched-btn').addEventListener('click', () => switchReportView('dispatched'));
    document.getElementById('view-outstanding-btn').addEventListener('click', () => switchReportView('outstanding'));

    // Preview modal listeners
    document.getElementById('close-preview-modal-btn').addEventListener('click', hidePreviewModal);
    document.getElementById('cancel-print-btn').addEventListener('click', hidePreviewModal);
    document.getElementById('confirm-print-btn').addEventListener('click', confirmAndPrint);

    // Invoice modal listeners
    document.getElementById('load-invoices-btn').addEventListener('click', openInvoiceModal);
    // Second button is optional (may not exist if Route/Area field was removed)
    const loadBtn2 = document.getElementById('load-invoices-btn-2');
    if (loadBtn2) loadBtn2.addEventListener('click', openInvoiceModal);
    document.getElementById('close-invoice-modal-btn').addEventListener('click', closeInvoiceModal);
    document.getElementById('add-selected-btn').addEventListener('click', addSelectedInvoices);
    document.getElementById('select-all-invoices').addEventListener('change', toggleSelectAll);
    document.getElementById('refresh-invoices-btn').addEventListener('click', refreshInvoices);

    // Header inputs save on change
    Object.values(formInputs).forEach(input => {
        input.addEventListener('change', saveState);
    });

    // Special listener for truck select
    formInputs.regNumber.addEventListener('change', handleTruckChange);

    // Show/hide Swift / 3PL consignment fields based on Delivery Type
    formInputs.deliveryType.addEventListener('change', () => { handleDeliveryTypeChange(); updateConsignmentColumn(); });
    formInputs.consignmentNumber.addEventListener('input', updateConsignmentColumn);
    handleDeliveryTypeChange();

    // Landing & Auth Listeners
    // If already authenticated, bypass login modal and restore straight into the app.
    // If not authenticated, open the login modal as before.
    document.getElementById('landing-manifest-btn').addEventListener('click', () => {
        if (getToken() && localStorage.getItem('currentUser')) {
            restoreSessionUI('manifest');
        } else {
            openLoginModal('manifest');
        }
    });
    document.getElementById('landing-report-btn').addEventListener('click', () => {
        if (getToken() && localStorage.getItem('currentUser')) {
            restoreSessionUI('report');
        } else {
            openLoginModal('report');
        }
    });
    document.getElementById('login-submit-btn').addEventListener('click', handleLogin);
    document.getElementById('close-login-btn').addEventListener('click', () => {
        document.getElementById('login-modal').classList.add('hidden');
        document.getElementById('login-modal').classList.remove('visible');
    });
    // Allow Enter key on password/username input
    document.getElementById('login-password').addEventListener('keyup', (e) => {
        if (e.key === 'Enter') handleLogin();
    });
    document.getElementById('login-username').addEventListener('keyup', (e) => {
        if (e.key === 'Enter') document.getElementById('login-password').focus();
    });

    // Invoice modal filter / search listeners
    const invoiceRouteFilter = document.getElementById('invoice-route-filter');
    if (invoiceRouteFilter) {
        invoiceRouteFilter.addEventListener('change', handleInvoiceRouteFilterChange);
    }
    const invoiceSearch = document.getElementById('invoice-search');
    if (invoiceSearch) {
        invoiceSearch.addEventListener('input', handleInvoiceSearch);
    }
    const clearInvoiceSearchBtn = document.getElementById('clear-invoice-search-btn');
    if (clearInvoiceSearchBtn) {
        clearInvoiceSearchBtn.addEventListener('click', clearInvoiceSearch);
    }

    initManualEntryRestoreListeners();
}

function setDefaultDate() {
    // Always set to current date (read-only field)
    formInputs.date.valueAsDate = new Date();
}

function getConsignmentDisplay() {
    const isSwift = formInputs.deliveryType.value === 'SWIFT_3PL';
    return isSwift && formInputs.consignmentNumber.value.trim()
        ? formInputs.consignmentNumber.value.trim()
        : '—';
}

function updateConsignmentColumn() {
    const display = getConsignmentDisplay();
    document.querySelectorAll('#manifest-table tbody .consignment-cell').forEach(cell => {
        cell.textContent = display;
    });
}

function handleDeliveryTypeChange() {
    const isSwift = formInputs.deliveryType.value === 'SWIFT_3PL';
    const swiftFields = document.getElementById('swift-consignment-fields');
    swiftFields.classList.toggle('hidden', !isSwift);

    if (isSwift) {
        if (!formInputs.thirdPartyProvider.value) formInputs.thirdPartyProvider.value = 'Swift';
        if (!formInputs.consignmentDate.value) formInputs.consignmentDate.value = formInputs.date.value;
    }
}

// Logic
async function addOrder() {
    const invoiceNum = orderInputs.invoice.value.trim();
    const customer   = orderInputs.customer.value.trim();
    const orderNum   = orderInputs.orderNumber.value.trim() || '';
    const area       = orderInputs.area.value.trim() || 'UNKNOWN';
    const value      = parseFloat(orderInputs.value.value) || 0;

    if (!invoiceNum || !customer) {
        alert('Please fill in at least Invoice Number and Customer Name.');
        return;
    }

    const btn = document.getElementById('add-order-btn');
    btn.disabled = true;

    try {
        // Single atomic call: create the invoice and stage it in one transaction
        const resp = await apiFetch(`${API_URL}/invoices/manual-and-stage`, {
            method: 'POST',
            body: JSON.stringify({
                invoice_number:  invoiceNum,
                order_number:    orderNum,
                customer_name:   customer,
                total_value:     String(value),
                area:            area,
                customer_number: 'N/A'
            })
        });

        if (!resp.ok) {
            const err = await resp.json().catch(() => ({}));
            alert(`Failed to add invoice: ${err.detail || resp.statusText}`);
            return;
        }

        // Refresh the manifest table from API, then clear the form
        await renderTable();
        clearOrderInputs();

    } catch (err) {
        console.error('Error adding order:', err);
        alert('An unexpected error occurred. Please try again.');
    } finally {
        btn.disabled = false;
    }
}

async function removeOrder(id) {
    if (confirm('Remove this order?')) {
        // Find the order to get its filename
        const order = orders.find(o => o.id === id);
        if (!order) return;

        // Call API to remove from staging
        try {
            const response = await apiFetch(`${API_URL}/manifest/remove`, {
                method: 'POST',
                body: JSON.stringify({ filenames: [order.filename || order.invoice] })
            });

            if (!response.ok) {
                console.warn('Could not remove invoice from staging');
            }
        } catch (error) {
            console.error('Error removing from staging:', error);
        }

        // Reload manifest from API to refresh the list
        await renderTable();
    }
}

function clearOrderInputs() {
    orderInputs.invoice.value = '';
    orderInputs.orderNumber.value = '';
    orderInputs.invoiceDate.value = '';
    orderInputs.customer.value = '';
    orderInputs.sku.value = '0';
    orderInputs.value.value = '0';
    orderInputs.weight.value = '0';

    // Keep area as it might be the same for the route
    // orderInputs.area.value = ''; 
    orderInputs.invoice.focus();
}

function calcTotals(orderList) {
    let sku = 0, value = 0, weight = 0;
    orderList.forEach(o => {
        sku    += (o.sku    || 0);
        value  += (o.value  || 0);
        weight += (o.weight || 0);
    });
    return { sku, value, weight };
}

async function renderTable() {
    // Reload from API first to ensure we have latest data
    await loadCurrentManifestFromAPI();

    tableBody.innerHTML = '';
    const { sku: tSku, weight: tWeight } = calcTotals(orders);
    const valueTotalsByCurrency = calcValueTotalsByCurrency(orders);

    const consignmentDisplay = getConsignmentDisplay();

    orders.forEach(order => {
        const row = document.createElement('tr');
        row.innerHTML = `
            <td>${order.invoice}</td>
            <td>${order.customer}</td>
            <td>${order.area}</td>
            <td>${order.sku}</td>
            <td>${formatCurrencyValue(order.value, order.currency)}</td>
            <td>${order.weight}</td>
            <td class="consignment-cell">${consignmentDisplay}</td>
            <td>
                <button onclick="removeOrder(${order.id})" class="btn-icon text-red-500">
                    <i data-lucide="trash-2"></i>
                </button>
            </td>
        `;
        tableBody.appendChild(row);
    });

    totalSkuEl.textContent = tSku;
    // Mixed USD/ZWL selections show one line per currency — never a blended sum.
    totalValueEl.innerHTML = formatTotalsByCurrency(valueTotalsByCurrency, 'value');
    totalWeightEl.textContent = tWeight.toFixed(1);
    orderCountEl.textContent = `${orders.length} Invoices`;

    lucide.createIcons();
}

function resetSystem() {
    if (confirm('Are you sure you want to reset everything? This will clear all current data.')) {
        orders = [];
        // Clear all inputs
        Object.values(formInputs).forEach(input => input.value = '');

        // Reset specific defaults
        setDefaultDate();
        formInputs.palletsBrown.value = 0;
        formInputs.palletsBlue.value = 0;
        formInputs.crates.value = 0;
        formInputs.mileage.value = 0;

        // Ensure dropdown is reset to default
        formInputs.regNumber.value = "";

        // Reset manifest number placeholder for the new session
        formInputs.manifestNumber.value = MANIFEST_PLACEHOLDER;

        // Reset 3PL / Swift consignment fields to default INTERNAL state
        formInputs.deliveryType.value = 'INTERNAL';
        formInputs.thirdPartyProvider.value = 'Swift';
        handleDeliveryTypeChange();

        saveState();
        renderTable();
    }
}

// Persistence
function saveState() {
    // Save form header data only (not orders - those come from API).
    // manifestNumber is intentionally excluded: it is owned by the backend
    // and must never be restored from localStorage.
    const state = {
        header: {}
    };
    Object.keys(formInputs).forEach(key => {
        if (key === 'manifestNumber') return;
        state.header[key] = formInputs[key].value;
    });
    localStorage.setItem('manifestAppState', JSON.stringify(state));
}

async function loadState() {
    // Load header data from localStorage.
    // manifestNumber is never restored — the backend owns it.
    // Any stale value written by an older version of this code is ignored here.
    const saved = localStorage.getItem('manifestAppState');
    if (saved) {
        const state = JSON.parse(saved);
        if (state.header) {
            Object.keys(formInputs).forEach(key => {
                if (key === 'manifestNumber') return;
                if (state.header[key]) formInputs[key].value = state.header[key];
            });
        }
    }

    handleDeliveryTypeChange();

    // Manifest items are loaded separately via renderTable().  Callers that
    // need fresh API data must call renderTable() after loadState().
}

// NEW: Load current manifest from staging API
async function loadCurrentManifestFromAPI() {
    // CLEAR FIRST - prevent showing stale data if API fails
    orders = [];

    // Skip API call if unauthenticated — both token and username must be present
    if (!getToken() || !localStorage.getItem('currentUser')) {
        return;
    }

    try {
        const response = await apiFetch(`${API_URL}/manifest/current`);

        if (!response.ok) {
            console.warn('Could not load current manifest from API');
            // orders already cleared above
            return;
        }

        const data = await response.json();
        const invoices = data.invoices || [];

        // Convert API invoice format to local orders format
        orders = invoices.filter(inv => {
            if (!inv.id) { console.error('Invoice missing id from API, skipping:', inv.filename); return false; }
            return true;
        }).map(inv => ({
            id: inv.id,
            filename: inv.filename,  // preserve DB filename for staging API calls
            invoice: inv.invoice_number || inv.filename,
            orderNumber: inv.order_number || '',
            customerNumber: inv.customer_number || 'N/A',
            invoiceDate: inv.invoice_date || 'N/A',
            customer: inv.customer_name,
            area: inv.area || 'UNKNOWN',
            sku: 0, // Default
            value: parseFloat(String(inv.total_value).replace(/[^0-9.-]/g, '')) || 0,
            currency: inv.currency || DEFAULT_CURRENCY,
            weight: 0, // Default
            timestamp: inv.date_processed || new Date().toISOString()
        }));

        console.log(`Loaded ${orders.length} invoices from current manifest`);
    } catch (error) {
        console.error('Error loading current manifest:', error);
        // orders already cleared above
    }
}

async function saveReport(manifestData) {
    try {
        const response = await apiFetch(`${API_URL}/reports`, {
            method: 'POST',
            body: JSON.stringify(manifestData)
        });

        if (response.ok) {
            const result = await response.json();
            console.log("Report saved to database:", result.manifest_number);
            // If the reports modal is open, refresh it
            if (!document.getElementById('reports-modal').classList.contains('hidden')) {
                renderReports();
            }
            return result; // { message, id, manifest_number }
        } else {
            console.error("Failed to save report to database:", response.status);
            return null;
        }
    } catch (e) {
        console.error("Error saving report:", e);
        return null;
    }
}

// Reports
let filteredReportData = []; // Store filtered data for export

function hideReports() {
    const modal = document.getElementById('reports-modal');
    modal.classList.remove('visible');
    modal.classList.add('hidden');

    // If not logged in, return to landing page
    if (!currentUser) {
        showLandingPage();
    }
}

function renderManifestView(manifest) {
    const list = document.getElementById('reports-list');
    const summaryEl = document.getElementById('report-summary');

    // Update summary with Manifest Details
    summaryEl.classList.remove('hidden');
    summaryEl.innerHTML = `
        <div style="display:flex; flex-direction:column; gap:0.5rem;">
            <div style="font-size: 1.25rem; font-weight: bold; color: #1e293b;">
                Manifest: ${manifest.manifest_number}
            </div>
            <div style="display:grid; grid-template-columns: repeat(4, 1fr); gap: 1rem; font-size: 0.9rem; color: #64748b;">
                <div><strong>Driver:</strong> ${manifest.driver || 'N/A'}</div>
                <div><strong>Truck:</strong> ${manifest.reg_number || 'N/A'}</div>
                <div><strong>Date:</strong> ${formatDate(manifest.date)}</div>
                <div><strong>Invoices:</strong> ${manifest.invoices.length}</div>
            </div>
            <div style="font-size: 0.8rem; margin-top: 0.5rem; color: #94a3b8;">
                <button onclick="renderReports()" style="background:none; border:none; text-decoration:underline; cursor:pointer; color: #3b82f6;">
                    &larr; Back to all reports
                </button>
            </div>
        </div>
    `;

    // Render Invoices for this Manifest
    list.innerHTML = '';

    if (!manifest.invoices || manifest.invoices.length === 0) {
        list.innerHTML = '<tr><td colspan="10" style="text-align:center;">No invoices found for this manifest.</td></tr>';
        return;
    }

    manifest.invoices.forEach(row => {
        const tr = document.createElement('tr');
        // Handle property name differences (report_items use underscores usually vs memory naming)
        // Adjusting based on DB schema: invoice_number, order_number etc.
        tr.innerHTML = `
            <td><strong>${row.invoice_number || 'N/A'}</strong></td>
            <td>${row.order_number || 'N/A'}</td>
            <td>${manifest.manifest_number}</td>
            <td>${manifest.reg_number || 'N/A'}</td>
            <td>${row.customer_name || 'N/A'}</td>
            <td>${row.customer_number || 'N/A'}</td>
            <td>${row.invoice_date || 'N/A'}</td>
            <td>${formatDate(manifest.date)}</td>
            <td>${manifest.driver || 'N/A'}</td>
            <td>${manifest.assistant || 'N/A'}</td>
            <td>${manifest.checker || 'N/A'}</td>
        `;
        list.appendChild(tr);
    });

    lucide.createIcons();
}

// Search filter handlers
async function handleSearchInput(e) {
    const searchTerm = e.target.value.trim();
    const clearBtn = document.getElementById('clear-search-btn');

    // Show/hide clear button
    if (searchTerm) {
        clearBtn.classList.remove('hidden');
    } else {
        clearBtn.classList.add('hidden');
    }

    // Check if it's a Manifest Number (simple heuristic or API check)
    // If it starts with 'M' and has digits, or just try to find it via API
    if (searchTerm.length > 2) {
        try {
            const response = await apiFetch(`${API_URL}/manifests/search/query?q=${encodeURIComponent(searchTerm)}`);
            const data = await response.json();

            if (data.match) {
                // Found a direct manifest match!
                renderManifestView(data.manifest);
                return;
            }
        } catch (err) {
            console.warn("Manifest search check failed", err);
        }
    }

    // Re-render with search filter (standard list filtering)
    renderReports();
}

function clearSearch() {
    const searchInput = document.getElementById('report-search');
    searchInput.value = '';
    document.getElementById('clear-search-btn').classList.add('hidden');
    renderReports();
}

// Export Dispatch Report to Excel
async function exportDispatchReport() {
    if (filteredReportData.length === 0) {
        alert('No data to export. Please generate a report first.');
        return;
    }

    const workbook = new ExcelJS.Workbook();
    const sheet = workbook.addWorksheet('Dispatch Report');

    // Set column widths
    sheet.columns = [
        { header: 'Invoice #', key: 'invoice', width: 15 },
        { header: 'Order #', key: 'orderNumber', width: 15 },
        { header: 'Manifest #', key: 'manifest', width: 15 },
        { header: 'Truck Reg', key: 'truckReg', width: 15 },
        { header: 'Customer Name', key: 'customer', width: 35 },
        { header: 'Customer #', key: 'customerNumber', width: 15 },
        { header: 'Invoice Date', key: 'invoiceDate', width: 15 }, // Added Invoice Date
        { header: 'Date Dispatched', key: 'date', width: 15 },
        { header: 'Driver', key: 'driver', width: 20 },
        { header: 'Assistant', key: 'assistant', width: 20 },
        { header: 'Checker', key: 'checker', width: 20 }
    ];

    // Title row
    const dateFrom = document.getElementById('report-date-from').value;
    const dateTo = document.getElementById('report-date-to').value;
    const fromText = dateFrom ? formatDate(dateFrom) : 'Beginning';
    const toText = dateTo ? formatDate(dateTo) : 'Today';

    sheet.mergeCells('A1:G1');
    sheet.getCell('A1').value = 'BRD DISTRIBUTION - DISPATCH REPORT';
    sheet.getCell('A1').font = { bold: true, size: 16 };
    sheet.getCell('A1').alignment = { horizontal: 'center' };

    sheet.mergeCells('A2:G2');
    sheet.getCell('A2').value = `Period: ${fromText} to ${toText}`;
    sheet.getCell('A2').font = { size: 12 };
    sheet.getCell('A2').alignment = { horizontal: 'center' };

    // Header row
    const headerRow = sheet.getRow(4);
    headerRow.values = ['Invoice #', 'Order #', 'Manifest #', 'Truck Reg', 'Customer Name', 'Customer #', 'Invoice Date', 'Date Dispatched', 'Driver Name', 'Driver Assistant', 'Checker Name'];
    headerRow.eachCell((cell) => {
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF4472C4' } };
        cell.font = { color: { argb: 'FFFFFFFF' }, bold: true };
        cell.alignment = { horizontal: 'center' };
        cell.border = { top: { style: 'thin' }, left: { style: 'thin' }, bottom: { style: 'thin' }, right: { style: 'thin' } };
    });

    // Data rows
    filteredReportData.forEach(row => {
        const dataRow = sheet.addRow([
            row.invoice,
            row.orderNumber,
            row.manifest || 'N/A',
            row.truckReg || 'N/A',
            row.customer,
            row.customerNumber,
            row.invoiceDate, // Added Invoice Date
            formatDate(row.dateDispatched),
            row.driver,
            row.assistant,
            row.checker
        ]);
        dataRow.eachCell((cell) => {
            cell.border = { top: { style: 'thin' }, left: { style: 'thin' }, bottom: { style: 'thin' }, right: { style: 'thin' } };
        });
    });

    // Summary row
    const summaryRow = sheet.addRow(['Total Invoices:', filteredReportData.length, '', '', '', '', '']);
    sheet.mergeCells(`B${summaryRow.number}:H${summaryRow.number}`);
    summaryRow.getCell(1).font = { bold: true };
    summaryRow.getCell(2).font = { bold: true };
    summaryRow.eachCell((cell) => {
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFD9D9D9' } };
        cell.border = { top: { style: 'thin' }, left: { style: 'thin' }, bottom: { style: 'thin' }, right: { style: 'thin' } };
    });

    // Write buffer and download
    const buffer = await workbook.xlsx.writeBuffer();
    const dateStr = new Date().toISOString().split('T')[0];
    saveBlob(buffer, `Dispatch_Report_${dateStr}.xlsx`);
}

// =============================================
// MANIFEST PREVIEW MODAL
// =============================================

function showPreviewModal() {
    if (orders.length === 0) {
        alert('No orders to print.');
        return;
    }

    // Populate preview data
    document.getElementById('preview-manifest-number').textContent = formInputs.manifestNumber.value;
    document.getElementById('preview-date').textContent = formatDate(formInputs.date.value);
    document.getElementById('preview-reg-number').textContent = formInputs.regNumber.value || 'N/A';
    document.getElementById('preview-driver').textContent = formInputs.driver.value || 'N/A';
    document.getElementById('preview-assistant').textContent = formInputs.assistant.value || 'N/A';
    document.getElementById('preview-checker').textContent = formInputs.checker.value || 'N/A';
    document.getElementById('preview-mileage').textContent = formInputs.mileage.value || '0';
    document.getElementById('preview-pallets-brown').textContent = formInputs.palletsBrown.value || '0';
    document.getElementById('preview-pallets-blue').textContent = formInputs.palletsBlue.value || '0';
    document.getElementById('preview-crates').textContent = formInputs.crates.value || '0';
    document.getElementById('preview-invoice-count').textContent = orders.length;

    // 3PL / Swift consignment details — only shown for SWIFT_3PL manifests
    const swiftSection = document.getElementById('preview-swift-section');
    if (formInputs.deliveryType.value === 'SWIFT_3PL') {
        document.getElementById('preview-third-party-provider').textContent = formInputs.thirdPartyProvider.value || 'Swift';
        document.getElementById('preview-consignment-number').textContent = formInputs.consignmentNumber.value || '—';
        document.getElementById('preview-consignment-date').textContent = formInputs.consignmentDate.value ? formatDate(formInputs.consignmentDate.value) : '—';
        document.getElementById('preview-consignment-notes').textContent = formInputs.consignmentNotes.value.trim() || '—';
        swiftSection.classList.remove('hidden');
    } else {
        swiftSection.classList.add('hidden');
    }

    // Populate orders table
    const previewOrdersList = document.getElementById('preview-orders-list');
    previewOrdersList.innerHTML = '';

    const { sku: tSku, weight: tWeight } = calcTotals(orders);
    const previewValueTotalsByCurrency = calcValueTotalsByCurrency(orders);

    orders.forEach(order => {
        const row = document.createElement('tr');
        row.innerHTML = `
            <td>${order.invoice}</td>
            <td>${order.customer}</td>
            <td>${order.area}</td>
            <td>${order.sku}</td>
            <td>${formatCurrencyValue(order.value, order.currency)}</td>
            <td>${order.weight}</td>
        `;
        previewOrdersList.appendChild(row);
    });

    // Update totals — mixed USD/ZWL selections show one line per currency.
    document.getElementById('preview-total-sku').textContent = tSku;
    document.getElementById('preview-total-value').innerHTML = formatTotalsByCurrency(previewValueTotalsByCurrency, 'value');
    document.getElementById('preview-total-weight').textContent = tWeight.toFixed(1);

    // Show modal
    const modal = document.getElementById('preview-modal');
    modal.classList.remove('hidden');
    modal.classList.add('visible');

    lucide.createIcons();
}

function hidePreviewModal() {
    const modal = document.getElementById('preview-modal');
    modal.classList.remove('visible');
    modal.classList.add('hidden');
}

async function confirmAndPrint() {
    // ── Step 1: Validate before any network call ──────────────────────────
    if (orders.length === 0) {
        alert('No orders to print.');
        return;
    }
    if (!formInputs.regNumber.value) {
        alert('Please select a Truck Registration number before processing the manifest.');
        const regInput = document.getElementById('reg-number');
        regInput.style.border = "2px solid red";
        regInput.focus();
        setTimeout(() => regInput.style.border = "", 3000);
        return;
    }
    if (formInputs.deliveryType.value === 'SWIFT_3PL' && !formInputs.consignmentNumber.value.trim()) {
        alert('Swift consignment number is required for 3PL deliveries.');
        const consignmentInput = formInputs.consignmentNumber;
        consignmentInput.style.border = "2px solid red";
        consignmentInput.focus();
        setTimeout(() => consignmentInput.style.border = "", 3000);
        return;
    }

    // ── Double-submit guard ───────────────────────────────────────────────
    const confirmBtn = document.getElementById('confirm-print-btn');
    if (confirmBtn && confirmBtn.disabled) return;
    if (confirmBtn) confirmBtn.disabled = true;

    try {

    // ── Step 2: Save report to backend — this generates the manifest number ─
    // Read assignment IDs from the data-user-id attribute set by
    // initPersonnelDropdowns() when the ADMIN user map is available.
    // Falls back to null for DISPATCH users — backend resolves by username.
    const driverOption    = formInputs.driver.options[formInputs.driver.selectedIndex];
    const assistantOption = formInputs.assistant.options[formInputs.assistant.selectedIndex];
    const driverUserId    = driverOption?.dataset?.userId    ? Number(driverOption.dataset.userId)    : null;
    const assistantUserId = assistantOption?.dataset?.userId ? Number(assistantOption.dataset.userId) : null;

    const reportResult = await saveReport({
        date: formInputs.date.value,
        regNumber: formInputs.regNumber.value,
        driver: formInputs.driver.value,
        assistant: formInputs.assistant.value,
        checker: formInputs.checker.value,
        driver_user_id: driverUserId,
        assistant_user_id: assistantUserId,
        palletsBrown: parseInt(formInputs.palletsBrown.value) || 0,
        palletsBlue: parseInt(formInputs.palletsBlue.value) || 0,
        crates: parseInt(formInputs.crates.value) || 0,
        mileage: parseInt(formInputs.mileage.value) || 0,
        deliveryType: formInputs.deliveryType.value,
        thirdPartyProvider: formInputs.thirdPartyProvider.value || null,
        consignmentNumber: formInputs.consignmentNumber.value.trim() || null,
        consignmentDate: formInputs.consignmentDate.value || null,
        consignmentNotes: formInputs.consignmentNotes.value || null,
        // totalSku / totalValue / totalWeight intentionally omitted:
        // the backend computes these from report_items after save.
        invoices: orders.map(o => ({
            num: o.invoice,
            orderNum: o.orderNumber,
            invoiceDate: o.invoiceDate,
            customerNumber: o.customerNumber || 'N/A',
            value: o.value,
            sku: o.sku || 0,
            weight: o.weight || 0,
            customer: o.customer
        }))
    });

    if (!reportResult) {
        alert('Warning: Report could not be saved to the database. The manifest was not finalized. Please try again.');
        await renderTable();
        return;
    }

    // ── Step 3: Update UI with the real backend-issued manifest number ─────
    const manifestNum = reportResult.manifest_number;
    formInputs.manifestNumber.value = manifestNum;

    // Also update the preview modal heading so the printed output is correct
    const previewNumEl = document.getElementById('preview-manifest-number');
    if (previewNumEl) previewNumEl.textContent = manifestNum;

    // ── Step 4: Print — manifest number field now shows the real number ────
    window.print();
    hidePreviewModal();

    // ── Step 5: Generate and download Excel using the real manifest number ─
    await generateExcel(manifestNum);

    // ── Step 6: Reset for next manifest ───────────────────────────────────
    formInputs.manifestNumber.value = MANIFEST_PLACEHOLDER;
    formInputs.deliveryType.value = 'INTERNAL';
    formInputs.thirdPartyProvider.value = 'Swift';
    formInputs.consignmentNumber.value = '';
    formInputs.consignmentDate.value = '';
    formInputs.consignmentNotes.value = '';
    handleDeliveryTypeChange();
    orders = [];
    setDefaultDate();
    saveState();
    await renderTable();

    } finally {
        if (confirmBtn) confirmBtn.disabled = false;
    }
}

// Excel Generation — pure file-building function.
// manifestNum must be the backend-issued number; never call this with a placeholder.
async function generateExcel(manifestNum) {
    const workbook = new ExcelJS.Workbook();
    const sheet = workbook.addWorksheet('Manifest');

    // Set column widths
    sheet.columns = [
        { width: 15 }, // A: Invoice
        { width: 30 }, // B: Customer Name
        { width: 15 }, // C: Customer Number
        { width: 15 }, // D: Area
        { width: 8 },  // E: SKU
        { width: 10 }, // F: Value
        { width: 10 }, // G: Weight
        { width: 10 }, // H: Date
        { width: 10 }, // I: Time In
        { width: 10 }, // J: Time Out
        { width: 15 }, // K: Sign
    ];

    // Row 8: Table Header
    const headerRow = sheet.getRow(8);
    headerRow.values = ['INVOICE', 'CUSTOMER NAME', 'ACCOUNT', 'AREA', 'SKU', 'VALUE', 'WEIGHT KG', 'DATE', 'TIME IN', 'TIME OUT', 'CUSTOMER SIGN'];
    headerRow.eachCell((cell) => {
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF4472C4' } };
        cell.font = { color: { argb: 'FFFFFFFF' }, bold: true };
        cell.alignment = { horizontal: 'center' };
        cell.border = { top: { style: 'thin' }, left: { style: 'thin' }, bottom: { style: 'thin' }, right: { style: 'thin' } };
    });

    // Data Rows
    // VALUE is written as "CUR 1,234.56" text (not a numeric $-formatted cell) —
    // a mixed USD/ZWL manifest must never look like a single-currency figure.
    orders.forEach(order => {
        const row = sheet.addRow([
            order.invoice,
            order.customer,
            order.customerNumber || 'N/A',
            order.area,
            order.sku,
            formatCurrencyValue(order.value, order.currency),
            order.weight,
            order.invoiceDate ? formatDate(order.invoiceDate) : '',
            '', '', ''
        ]);
        row.eachCell((cell) => {
            cell.border = { top: { style: 'thin' }, left: { style: 'thin' }, bottom: { style: 'thin' }, right: { style: 'thin' } };
        });
    });

    // Totals Row — one line per currency in the VALUE cell, never blended.
    // Column indices match the header row (E=SKU, F=Value, G=Weight); a
    // pre-existing off-by-one here previously put the SKU total under Area
    // and the value/weight totals one column left of their headers, which
    // would have put this currency breakdown under the wrong column too.
    const lastRow = sheet.lastRow.number + 1;
    const totalRow = sheet.getRow(lastRow);
    const excelTotals = calcTotals(orders);
    const excelValueTotalsByCurrency = calcValueTotalsByCurrency(orders);
    totalRow.getCell(1).value = 'Grand Total';
    totalRow.getCell(5).value = excelTotals.sku;
    totalRow.getCell(6).value = excelValueTotalsByCurrency
        .map(t => formatCurrencyValue(t.value, t.currency))
        .join('\n');
    totalRow.getCell(6).alignment = { wrapText: true };
    totalRow.getCell(7).value = excelTotals.weight;
    totalRow.eachCell((cell) => {
        cell.font = { bold: true };
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFD9D9D9' } };
        cell.border = { top: { style: 'thin' }, left: { style: 'thin' }, bottom: { style: 'thin' }, right: { style: 'thin' } };
    });

    const buffer = await workbook.xlsx.writeBuffer();
    const fileName = `Manifest_${manifestNum}.xlsx`;

    saveBlob(buffer, fileName);

    const blob = new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
    uploadManifest(blob, fileName);
}

function saveBlob(buffer, fileName) {
    const blob = new Blob([buffer], { type: 'application/octet-stream' });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = fileName;
    link.click();
}

async function uploadManifest(blob, filename) {
    const formData = new FormData();
    formData.append('file', blob, filename);

    try {
        const response = await apiFetch(`${API_URL}/manifests/save`, {
            method: 'POST',
            body: formData
        });

        if (!response.ok) {
            console.warn('Failed to save manifest to server');
        } else {
            console.log('Manifest saved to server');
        }
    } catch (error) {
        console.error('Error uploading manifest:', error);
    }
}

function formatDate(dateStr) {
    if (!dateStr) return '';
    const d = new Date(dateStr);
    const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
    return `${d.getDate()}-${months[d.getMonth()]}-${d.getFullYear().toString().substr(-2)}`;
}

// =============================================
// INVOICE API & MODAL FUNCTIONS
// =============================================

async function fetchInvoices(area = null) {
    try {
        let url = `${API_URL}/invoices`;
        if (area) {
            url += `?area=${encodeURIComponent(area)}`;
        }

        const response = await apiFetch(url);
        if (!response.ok) {
            throw new Error('Failed to fetch invoices');
        }
        const data = await response.json();
        availableInvoices = data.invoices;
        return data.invoices;
    } catch (error) {
        console.error('Error fetching invoices:', error);
        alert('Could not load invoices. Make sure the API server is running (python api_server.py)');
        return [];
    }
}

function closeInvoiceModal() {
    const modal = document.getElementById('invoice-modal');
    modal.classList.remove('visible');
    modal.classList.add('hidden');
}

async function loadInvoicesIntoModal(area = null) {
    const tableBody = document.getElementById('invoice-select-list');
    tableBody.innerHTML = '<tr><td colspan="6" style="text-align:center;">Loading...</td></tr>';

    const invoices = await fetchInvoices(area);

    tableBody.innerHTML = '';

    if (invoices.length === 0) {
        tableBody.innerHTML = '<tr><td colspan="6" style="text-align:center; color: #64748b;">No invoices available</td></tr>';
        return;
    }

    invoices.forEach((inv, index) => {
        const row = document.createElement('tr');
        row.dataset.index = index;
        row.innerHTML = `
            <td><input type="checkbox" class="invoice-checkbox" data-index="${index}"></td>
            <td>${inv.invoice_number || 'N/A'}</td>
            <td>${inv.order_number || 'N/A'}</td>
            <td>${inv.invoice_date || 'N/A'}</td>
            <td>${inv.customer_name}</td>
            <td>${formatCurrencyValue(inv.total_value, inv.currency)}</td>
            <td>${inv.date_processed}</td>
        `;
        tableBody.appendChild(row);
    });

    // Add click listeners to checkboxes
    document.querySelectorAll('.invoice-checkbox').forEach(cb => {
        cb.addEventListener('change', updateSelectedCount);
    });

    updateSelectedCount();
    lucide.createIcons();
}

function toggleSelectAll(e) {
    const isChecked = e.target.checked;
    document.querySelectorAll('.invoice-checkbox').forEach(cb => {
        cb.checked = isChecked;
        cb.closest('tr').classList.toggle('selected', isChecked);
    });
    updateSelectedCount();
}

function updateSelectedCount() {
    const selected = document.querySelectorAll('.invoice-checkbox:checked').length;
    document.getElementById('selected-count').textContent = `${selected} selected`;

    // Update row highlighting
    document.querySelectorAll('.invoice-checkbox').forEach(cb => {
        cb.closest('tr').classList.toggle('selected', cb.checked);
    });
}

async function addSelectedInvoices() {
    const selectedCheckboxes = document.querySelectorAll('.invoice-checkbox:checked');

    if (selectedCheckboxes.length === 0) {
        alert('Please select at least one invoice.');
        return;
    }

    const filenamesToAllocate = [];

    selectedCheckboxes.forEach(cb => {
        const index = parseInt(cb.dataset.index);
        const inv = availableInvoices[index];
        filenamesToAllocate.push(inv.filename);
    });

    // Call API to add to staging
    let allocResult = { added: 0, taken: 0 };
    if (filenamesToAllocate.length > 0) {
        allocResult = await allocateInvoices(filenamesToAllocate);
    }

    // Reload manifest from API to get updated list
    await renderTable();

    // Uncheck all selected checkboxes after adding
    selectedCheckboxes.forEach(cb => {
        cb.checked = false;
        cb.closest('tr').classList.remove('selected');
    });

    // Reset Select All checkbox
    document.getElementById('select-all-invoices').checked = false;

    // Update the selected count display
    updateSelectedCount();

    // Feedback based on actual API result
    if (allocResult.error) {
        alert(`Failed to stage invoices: ${allocResult.error}`);
    } else {
        const parts = [];
        if (allocResult.added > 0) parts.push(`Added ${allocResult.added} invoice${allocResult.added !== 1 ? 's' : ''}`);
        if (allocResult.taken > 0) parts.push(`${allocResult.taken} already claimed by another session`);
        if (allocResult.not_found > 0) parts.push(`${allocResult.not_found} not found`);
        alert(parts.length ? parts.join('; ') + '.' : 'No invoices were staged.');
    }
}


async function allocateInvoices(filenames) {
    try {
        const response = await apiFetch(`${API_URL}/invoices/allocate`, {
            method: 'POST',
            body: JSON.stringify({ filenames: filenames })
        });

        const data = await response.json().catch(() => ({}));
        if (!response.ok) {
            console.error('Could not stage invoices:', data.detail || response.statusText);
            return { added: 0, taken: 0, error: data.detail || response.statusText };
        }
        return data; // { added, taken, already_yours, not_found, message }
    } catch (error) {
        console.error('Allocation API call failed:', error);
        return { added: 0, taken: 0, error: String(error) };
    }
}

async function refreshInvoices() {
    const refreshBtn = document.getElementById('refresh-invoices-btn');
    refreshBtn.disabled = true;
    refreshBtn.innerHTML = '<i data-lucide="loader-2"></i> Scanning...';
    lucide.createIcons();

    try {
        // Trigger a rescan of PDFs on the server
        await apiFetch(`${API_URL}/invoices/refresh`, { method: 'POST' });

        // Reload the modal
        const selectedArea = null;
        await loadInvoicesIntoModal(selectedArea);

    } catch (error) {
        console.error('Refresh failed:', error);
    } finally {
        refreshBtn.disabled = false;
        refreshBtn.innerHTML = '<i data-lucide="refresh-cw"></i> Refresh';
        lucide.createIcons();
    }
}

// =============================================
// SETTINGS MODAL FUNCTIONS
// =============================================

function populateTruckFormDropdowns() {
    // Populate driver dropdown
    const driverSelect = document.getElementById('new-truck-driver');
    driverSelect.innerHTML = '<option value="">Default Driver (optional)</option>';
    settingsData.drivers.forEach(name => {
        const option = document.createElement('option');
        option.value = name;
        option.textContent = name;
        driverSelect.appendChild(option);
    });

    // Populate assistant dropdown
    const assistantSelect = document.getElementById('new-truck-assistant');
    assistantSelect.innerHTML = '<option value="">Default Assistant (optional)</option>';
    settingsData.assistants.forEach(name => {
        const option = document.createElement('option');
        option.value = name;
        option.textContent = name;
        assistantSelect.appendChild(option);
    });

    // Populate checker dropdown
    const checkerSelect = document.getElementById('new-truck-checker');
    checkerSelect.innerHTML = '<option value="">Default Checker (optional)</option>';
    settingsData.checkers.forEach(name => {
        const option = document.createElement('option');
        option.value = name;
        option.textContent = name;
        checkerSelect.appendChild(option);
    });
}


// =============================================
// CUSTOMER-ROUTE MANAGEMENT FUNCTIONS
// =============================================

// Get the route assigned to a customer name (supports partial matching)
function getRouteForCustomer(customerName) {
    if (!customerName || !settingsData.customerRoutes || !settingsData.customerRoutes.length) return null;
    // Case-insensitive lookup with partial matching
    const normalizedName = customerName.trim().toUpperCase();

    // First try exact match
    for (const entry of settingsData.customerRoutes) {
        if (entry.customer_name.toUpperCase() === normalizedName) {
            return entry.route_name;
        }
    }

    // Then try partial match (customer name contains the pattern)
    // Sort by pattern length descending to match longest patterns first
    const sortedEntries = [...settingsData.customerRoutes]
        .sort((a, b) => b.customer_name.length - a.customer_name.length);

    for (const entry of sortedEntries) {
        const pattern = entry.customer_name.toUpperCase();
        // Check if the invoice customer name contains the assigned pattern
        if (normalizedName.includes(pattern)) {
            return entry.route_name;
        }
    }

    return null;
}

// Populate route filter dropdowns in modals
function populateRouteFilterDropdowns() {
    // Invoice modal route filter
    const invoiceFilter = document.getElementById('invoice-route-filter');
    if (invoiceFilter) {
        invoiceFilter.innerHTML = '<option value="">All Routes</option>';
        settingsData.routes.forEach(route => {
            const option = document.createElement('option');
            option.value = route;
            option.textContent = route;
            invoiceFilter.appendChild(option);
        });
    }

    // Report modal route filter
    const reportFilter = document.getElementById('report-route-filter');
    if (reportFilter) {
        reportFilter.innerHTML = '<option value="">All Routes</option>';
        settingsData.routes.forEach(route => {
            const option = document.createElement('option');
            option.value = route;
            option.textContent = route;
            reportFilter.appendChild(option);
        });
    }
}

// =============================================
// UPDATED INVOICE FILTERING WITH ROUTE
// =============================================

async function loadInvoicesIntoModalFiltered(area = null, routeFilter = null) {
    const tableBody = document.getElementById('invoice-select-list');
    tableBody.innerHTML = '<tr><td colspan="7" style="text-align:center;">Loading...</td></tr>';

    // Fetch latest data (populates availableInvoices)
    await fetchInvoices(area);

    // Render with filters
    renderFilteredInvoices();
}

// Render invoices applying both Route and Search filters locally
function renderFilteredInvoices() {
    const tableBody = document.getElementById('invoice-select-list');
    const routeFilter = document.getElementById('invoice-route-filter').value;
    const searchInput = document.getElementById('invoice-search');
    const searchTerm = searchInput ? searchInput.value.trim().toLowerCase() : '';

    const clearBtn = document.getElementById('clear-invoice-search-btn');
    if (clearBtn) {
        if (searchTerm) {
            clearBtn.classList.remove('hidden');
        } else {
            clearBtn.classList.add('hidden');
        }
    }

    tableBody.innerHTML = '';

    let filteredInvoices = availableInvoices;

    // Apply Route Filter
    if (routeFilter) {
        filteredInvoices = filteredInvoices.filter(inv => {
            const customerRoute = getRouteForCustomer(inv.customer_name);
            return customerRoute && customerRoute.toUpperCase() === routeFilter.toUpperCase();
        });
    }

    // Apply Search Filter
    if (searchTerm) {
        filteredInvoices = filteredInvoices.filter(inv => {
            const invNum = (inv.invoice_number || '').toLowerCase();
            const orderNum = (inv.order_number || '').toLowerCase();
            const custName = (inv.customer_name || '').toLowerCase();
            return invNum.includes(searchTerm) || orderNum.includes(searchTerm) || custName.includes(searchTerm);
        });
    }

    if (filteredInvoices.length === 0) {
        let message = 'No invoices available';
        if (routeFilter || searchTerm) {
            message = 'No invoices match your filters';
        }
        tableBody.innerHTML = `<tr><td colspan="7" style="text-align:center; color: #64748b;">${message}</td></tr>`;
        return;
    }

    filteredInvoices.forEach((inv) => {
        // Use original index from availableInvoices to ensure correct selection binding
        const originalIndex = availableInvoices.indexOf(inv);

        const row = document.createElement('tr');
        row.dataset.index = originalIndex;
        row.innerHTML = `
            <td><input type="checkbox" class="invoice-checkbox" data-index="${originalIndex}"></td>
            <td>${inv.invoice_number || 'N/A'}</td>
            <td>${inv.order_number || 'N/A'}</td>
            <td>${inv.invoice_date || 'N/A'}</td>
            <td>${inv.customer_name}</td>
            <td>${formatCurrencyValue(inv.total_value, inv.currency)}</td>
            <td>${inv.date_processed}</td>
        `;
        tableBody.appendChild(row);
    });

    // Add click listeners to checkboxes
    document.querySelectorAll('.invoice-checkbox').forEach(cb => {
        cb.addEventListener('change', updateSelectedCount);
    });

    updateSelectedCount();
    lucide.createIcons();
}

// Handle route filter change in invoice modal
function handleInvoiceRouteFilterChange() {
    renderFilteredInvoices();
}

function handleInvoiceSearch() {
    renderFilteredInvoices();
}

function clearInvoiceSearch() {
    const input = document.getElementById('invoice-search');
    if (input) {
        input.value = '';
        handleInvoiceSearch();
        input.focus();
    }
}

// =============================================
// UPDATED REPORT FILTERING WITH ROUTE
// =============================================

async function renderReports() {
    const list = document.getElementById('reports-list');
    list.innerHTML = '<tr><td colspan="11" style="text-align:center; padding: 2rem;">Loading reports...</td></tr>';

    // Ensure Manifest header is visible
    const manifestHeader = document.querySelector('#reports-table th:nth-child(3)');
    if (manifestHeader) manifestHeader.style.display = '';

    const dateFrom = document.getElementById('report-date-from').value;
    const dateTo = document.getElementById('report-date-to').value;
    const routeFilter = document.getElementById('report-route-filter').value;

    // FETCH DATA FROM API - Use /reports/dispatched for consistency with renderReports()
    try {
        const params = new URLSearchParams();
        if (dateFrom) params.append('date_from', dateFrom);
        if (dateTo) params.append('date_to', dateTo);

        const response = await apiFetch(`${API_URL}/reports/dispatched?${params.toString()}`);
        if (!response.ok) throw new Error("Failed to fetch reports");

        const data = await response.json();

        // Transform invoice-level data (already flattened by API)
        filteredReportData = (data.invoices || []).map(inv => ({
            invoice: inv.invoice_number || 'N/A',
            orderNumber: inv.order_number || 'N/A',
            manifest: inv.manifest_number || 'N/A',
            truckReg: inv.reg_number || 'N/A',
            customer: inv.customer_name || 'N/A',
            customerNumber: inv.customer_number || 'N/A',
            invoiceDate: inv.invoice_date || 'N/A',
            dateDispatched: inv.date_dispatched || 'N/A', // CORRECT: uses dispatch timestamp
            driver: inv.driver || 'N/A',
            assistant: inv.assistant || 'N/A',
            checker: inv.checker || 'N/A'
        }));

        // Apply route filter if specified
        if (routeFilter) {
            filteredReportData = filteredReportData.filter(inv => {
                const customerRoute = getRouteForCustomer(inv.customer);
                // Match logic: customer MUST have a route and it MUST match
                return customerRoute && customerRoute.toUpperCase() === routeFilter.toUpperCase();
            });
        }
    } catch (e) {
        console.error("Error fetching reports:", e);
        list.innerHTML = '<tr><td colspan="11" style="text-align:center; color: red;">Error loading reports.</td></tr>';
        return;
    }

    // Sort by date (newest first)
    filteredReportData.sort((a, b) => new Date(b.dateDispatched) - new Date(a.dateDispatched));

    // Apply search filter
    const searchTerm = document.getElementById('report-search').value.trim().toLowerCase();
    let displayData = filteredReportData;

    if (searchTerm) {
        displayData = filteredReportData.filter(row => {
            const invoiceMatch = row.invoice.toLowerCase().includes(searchTerm);
            const orderMatch = row.orderNumber.toLowerCase().includes(searchTerm);
            const customerMatch = row.customer.toLowerCase().includes(searchTerm);
            const manifestMatch = (row.manifest || '').toLowerCase().includes(searchTerm);
            return invoiceMatch || orderMatch || customerMatch || manifestMatch;
        });
    }

    list.innerHTML = '';

    // Render rows
    if (displayData.length === 0) {
        const message = searchTerm
            ? 'No invoices match your search criteria.'
            : routeFilter
                ? `No dispatched orders found for route "${routeFilter}".`
                : 'No dispatched orders found for the selected date range.';
        list.innerHTML = `<tr><td colspan="11" style="text-align:center; color: #64748b; padding: 2rem;">${message}</td></tr>`;
    } else {
        displayData.forEach(row => {
            const tr = document.createElement('tr');
            tr.innerHTML = `
                <td><strong>${row.invoice}</strong></td>
                <td>${row.orderNumber}</td>
                <td>${row.manifest}</td>
                <td>${row.truckReg}</td>
                <td>${row.customer}</td>
                <td>${row.customerNumber || 'N/A'}</td>
                <td>${row.invoiceDate}</td>
                <td>${formatDate(row.dateDispatched)}</td>
                <td>${row.driver}</td>
                <td>${row.assistant}</td>
                <td>${row.checker}</td>
            `;
            list.appendChild(tr);
        });
    }

    // Update summary
    const summaryEl = document.getElementById('report-summary');
    const countEl = document.getElementById('report-count');

    if (filteredReportData.length > 0 && (dateFrom || dateTo)) {
        summaryEl.classList.remove('hidden');
        const fromText = dateFrom ? formatDate(dateFrom) : 'Beginning';
        const toText = dateTo ? formatDate(dateTo) : 'Today';
        const routeText = routeFilter ? ` | Route: ${routeFilter}` : '';
        summaryEl.innerHTML = `
            <span class="report-summary-text">Dispatch Report: ${fromText} to ${toText}${routeText}</span>
            <span class="report-summary-count">${filteredReportData.length} invoices</span>
        `;
    } else {
        summaryEl.classList.add('hidden');
    }

    currentPrintableData = displayData;
    countEl.textContent = `${displayData.length} invoices found`;

    lucide.createIcons();
}

// Filter function wired to filter-btn.
async function filterReports() {
    const btn = document.getElementById('filter-btn');
    const originalContent = btn.innerHTML;

    try {
        // Set loading state
        btn.disabled = true;
        btn.innerHTML = '<i data-lucide="loader-2" class="spin"></i> Generating...';
        lucide.createIcons();

        // Allow UI to update
        await new Promise(resolve => setTimeout(resolve, 50));

        if (currentReportView === 'outstanding') {
            await renderOutstandingOrders();
        } else {
            renderReports();
        }
    } catch (error) {
        console.error('Error generating report:', error);
    } finally {
        // Restore button state
        btn.disabled = false;
        btn.innerHTML = originalContent;
        lucide.createIcons();
    }
}



function openInvoiceModal() {
    const selectedArea = null;
    document.getElementById('invoice-area-label').textContent = 'Area: All';

    // Populate route filter dropdown
    populateRouteFilterDropdowns();

    // Reset route filter to "All Routes"
    const routeFilter = document.getElementById('invoice-route-filter');
    if (routeFilter) {
        routeFilter.value = '';
    }

    const modal = document.getElementById('invoice-modal');
    modal.classList.remove('hidden');
    modal.classList.add('visible');
    loadInvoicesIntoModalFiltered(selectedArea, null);
}

function showReports() {
    const modal = document.getElementById('reports-modal');
    modal.classList.remove('hidden');
    modal.classList.add('visible');

    // Set default date range to current month
    const today = new Date();
    const firstDayOfMonth = new Date(today.getFullYear(), today.getMonth(), 1);

    document.getElementById('report-date-from').valueAsDate = firstDayOfMonth;
    document.getElementById('report-date-to').valueAsDate = today;

    // Populate route filter dropdown
    populateRouteFilterDropdowns();

    // Reset route filter
    const routeFilter = document.getElementById('report-route-filter');
    if (routeFilter) {
        routeFilter.value = '';
    }

    renderReports();
}

// Global state to track current view
let currentPrintableData = [];

function switchReportView(view) {
    currentReportView = view;

    // Update button states
    const dispatchedBtn = document.getElementById('view-dispatched-btn');
    const outstandingBtn = document.getElementById('view-outstanding-btn');

    if (view === 'dispatched') {
        dispatchedBtn.classList.add('active');
        outstandingBtn.classList.remove('active');
        renderReports();
    } else {
        dispatchedBtn.classList.remove('active');
        outstandingBtn.classList.add('active');
        renderOutstandingOrders();
    }
}

async function renderOutstandingOrders() {
    const list = document.getElementById('reports-list');
    const summaryEl = document.getElementById('report-summary');
    const countEl = document.getElementById('report-count');

    // Hide Manifest header
    const manifestHeader = document.querySelector('#reports-table th:nth-child(3)');
    if (manifestHeader) manifestHeader.style.display = 'none';

    list.innerHTML = '<tr><td colspan="11" style="text-align:center;">Loading outstanding orders...</td></tr>';
    summaryEl.classList.add('hidden');

    try {
        // Fetch pending invoices from API
        const response = await apiFetch(`${API_URL}/invoices`);
        if (!response.ok) throw new Error('Failed to fetch outstanding orders');

        const data = await response.json();
        let outstandingInvoices = data.invoices || [];

        // Apply route filter
        const routeFilter = document.getElementById('report-route-filter').value;
        if (routeFilter) {
            outstandingInvoices = outstandingInvoices.filter(inv => {
                const customerRoute = getRouteForCustomer(inv.customer_name);
                return customerRoute && customerRoute.toUpperCase() === routeFilter.toUpperCase();
            });
        }

        // Apply search filter
        const searchTerm = document.getElementById('report-search').value.trim().toLowerCase();
        if (searchTerm) {
            outstandingInvoices = outstandingInvoices.filter(inv => {
                const invNum = (inv.invoice_number || '').toLowerCase();
                const orderNum = (inv.order_number || '').toLowerCase();
                const custName = (inv.customer_name || '').toLowerCase();
                return invNum.includes(searchTerm) || orderNum.includes(searchTerm) || custName.includes(searchTerm);
            });
        }

        // Save for printing
        currentPrintableData = outstandingInvoices.map(inv => ({
            invoice: inv.invoice_number || 'N/A',
            orderNumber: inv.order_number || 'N/A',
            manifest: 'Pending',
            truckReg: '-',
            customer: inv.customer_name || 'N/A',
            invoiceDate: inv.invoice_date || 'N/A',
            dateDispatched: 'Pending',
            driver: '-',
            assistant: '-',
            checker: '-'
        }));

        list.innerHTML = '';

        if (outstandingInvoices.length === 0) {
            const message = searchTerm || routeFilter
                ? 'No outstanding orders match your filters.'
                : 'No outstanding orders found. All invoices have been dispatched!';
            list.innerHTML = `<tr><td colspan="11" style="text-align:center; color: #64748b; padding: 2rem;">${message}</td></tr>`;
        } else {
            outstandingInvoices.forEach(inv => {
                const tr = document.createElement('tr');
                tr.style.backgroundColor = '#fff7ed'; // Light orange background for outstanding
                tr.innerHTML = `
                    <td><strong>${inv.invoice_number || 'N/A'}</strong></td>
                    <td>${inv.order_number || 'N/A'}</td>
                    <td>-</td>
                    <td>${inv.customer_name || 'N/A'}</td>
                    <td>${inv.customer_number || 'N/A'}</td>
                    <td>${inv.invoice_date || 'N/A'}</td>
                    <td style="color: #f59e0b; font-weight: 600;">Pending</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                `;
                list.appendChild(tr);
            });
        }

        countEl.textContent = `${outstandingInvoices.length} outstanding orders`;

        // Update summary
        if (outstandingInvoices.length > 0) {
            summaryEl.classList.remove('hidden');
            const routeText = routeFilter ? ` | Route: ${routeFilter}` : '';
            summaryEl.innerHTML = `
                <span class="report-summary-text">Outstanding Orders${routeText}</span>
                <span class="report-summary-count">${outstandingInvoices.length} pending</span>
            `;
        }

    } catch (error) {
        console.error('Error fetching outstanding orders:', error);
        list.innerHTML = '<tr><td colspan="11" style="text-align:center; color: red;">Error loading outstanding orders. Please try again.</td></tr>';
    }

    lucide.createIcons();
}

// --- RBAC & Landing Page Functions ---

function showLandingPage() {
    const landing = document.getElementById('landing-overlay');
    if (landing) {
        landing.style.display = '';
        landing.classList.remove('hidden');
        landing.style.opacity = '1';
        landing.style.pointerEvents = 'auto';
    }
}

function hideLandingPage() {
    const landing = document.getElementById('landing-overlay');
    if (landing) {
        landing.classList.add('hidden');
        // Remove inline styles that override hidden class
        landing.style.opacity = '';
        landing.style.pointerEvents = '';
        landing.style.display = 'none'; // Force hide
    }
}

/**
 * Restore the app UI for an already-authenticated user without re-running login.
 * Called when index.html loads and localStorage already contains a valid session,
 * or when a landing card is clicked while a session is already active.
 *
 * @param {string} [intent] - 'manifest' | 'report' | undefined
 *   undefined  → default view for the user's role
 *   'report'   → open the reports modal immediately
 *   'manifest' → show manifest view (default for ADMIN/DISPATCH)
 */
function restoreSessionUI(intent) {
    // Hydrate runtime variables from localStorage (set during original login)
    currentUser     = localStorage.getItem('currentUser');
    currentUserRole = localStorage.getItem('userRole') || ROLE_REPORTS_ONLY;
    // currentUserId is not persisted to localStorage; leave null (only needed for
    // the settings page "YOU" badge, which lives in settings.js now)

    // Dismiss landing overlay
    hideLandingPage();

    // Apply role-based UI visibility
    applyPermissions();

    // Navigate to the appropriate view:
    // - Reports-only users cannot use the manifest, so always open reports
    // - An explicit 'report' intent also opens reports
    // - Everything else stays on the default manifest view
    if (intent === 'report' || currentUserRole === ROLE_REPORTS_ONLY) {
        showReports();
    }
}

function openLoginModal(intent) {
    loginIntent = intent;
    const modal = document.getElementById('login-modal');
    modal.classList.remove('hidden');
    modal.classList.add('visible');

    // Reset fields
    document.getElementById('login-username').value = '';
    document.getElementById('login-password').value = '';
    document.getElementById('login-error').classList.add('hidden');
    document.getElementById('access-error').classList.add('hidden');

    setTimeout(() => document.getElementById('login-username').focus(), 100);
}

async function handleLogin() {
    const usernameEl = document.getElementById('login-username');
    const passwordEl = document.getElementById('login-password');
    const loginBtn = document.getElementById('login-submit-btn');
    const loginError = document.getElementById('login-error');
    const accessError = document.getElementById('access-error');

    const username = usernameEl.value.trim();
    const password = passwordEl.value;

    // Validate inputs before sending
    if (!username || !password) {
        loginError.textContent = 'Please enter both username and password.';
        loginError.classList.remove('hidden');
        accessError.classList.add('hidden');
        return;
    }

    // Reset error messages
    loginError.classList.add('hidden');
    accessError.classList.add('hidden');

    // Show loading state on button
    loginBtn.disabled = true;
    loginBtn.innerHTML = '<i data-lucide="loader-2" class="spin"></i> Logging in...';
    lucide.createIcons();

    console.log(`[Login] Attempting login for user: "${username}"`);

    try {
        const response = await fetch('/api/auth/login', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ username, password })
        });

        console.log(`[Login] Server responded with status: ${response.status}`);

        if (response.status === 401) {
            // Invalid credentials
            console.warn('[Login] Invalid credentials.');
            loginError.textContent = 'Incorrect username or password.';
            loginError.classList.remove('hidden');
            passwordEl.value = '';
            passwordEl.focus();
            return;
        }

        if (!response.ok) {
            // Other server errors (500, 503 etc.)
            const detail = await response.text();
            console.error(`[Login] Server error ${response.status}:`, detail);
            loginError.textContent = `Server error (${response.status}). Please try again later.`;
            loginError.classList.remove('hidden');
            return;
        }

        const data = await response.json();
        console.log('[Login] Login successful. User data received:', data.user);

        // Store JWT token
        accessToken = data.access_token || null;
        if (accessToken) setToken(accessToken);

        const user = {
            id: data.user.id,
            username: data.user.username,
            role: data.user.role || ROLE_REPORTS_ONLY,
            isActive: data.user.isActive !== false,
        };

        // Check permissions based on what the user intends to do
        if (loginIntent === 'manifest') {
            if (user.role === ROLE_ADMIN || user.role === ROLE_DISPATCH) {
                console.log('[Login] Manifest access granted (role=' + user.role + ').');
                finalizeLogin(user);
            } else {
                console.warn('[Login] User lacks manifest permission (role=' + user.role + ').');
                accessError.textContent = 'You do not have permission to access the Manifest system. Reports Only access.';
                accessError.classList.remove('hidden');
                loginError.classList.add('hidden');
            }
        } else {
            // Report intent - all authenticated users can view reports
            console.log('[Login] Report access granted.');
            finalizeLogin(user);
        }

    } catch (error) {
        // Network-level failure (no connection, DNS failure, CORS etc.)
        console.error('[Login] Network error during login:', error);
        loginError.textContent = 'Could not connect to the server. Check your network connection.';
        loginError.classList.remove('hidden');
    } finally {
        loginBtn.disabled = false;
        loginBtn.textContent = 'Login';
    }
}

async function finalizeLogin(user) {
    currentUser = user.username;
    currentUserId = user.id;
    currentUserRole = user.role || ROLE_REPORTS_ONLY;
    setCurrentUser(user.username);
    setUserRole(user.role);


    // Run the full authenticated dashboard init (skipped at startup because
    // the user was unauthenticated when DOMContentLoaded fired).
    await loadSettings();
    initTruckDropdown();
    initPersonnelDropdowns();
    await loadState();
    initManifestNumber();
    setDefaultDate();
    renderTable();
    if (formInputs.regNumber.value) {
        handleTruckChange();
    }

    // If manifest number is missing, set placeholder (backend assigns on save)
    if (!formInputs.manifestNumber.value) {
        formInputs.manifestNumber.value = MANIFEST_PLACEHOLDER;
    }


    // Hide Modal & Landing
    document.getElementById('login-modal').classList.remove('visible');
    document.getElementById('login-modal').classList.add('hidden');
    hideLandingPage();

    // Apply UI Permissions
    applyPermissions();

    // Navigate if needed
    if (loginIntent === 'report') {
        showReports();
    }
}

function applyPermissions() {
    if (!currentUser) return;

    console.log("Applying permissions - User:", currentUser, "Role:", currentUserRole);

    const formSections = document.querySelectorAll('.form-section');
    const previewSection = document.querySelector('.preview-section');
    const settingsBtn = document.getElementById('settings-btn');
    const resetBtn = document.getElementById('reset-btn');

    const isAdmin    = currentUserRole === ROLE_ADMIN;
    const isDispatch = currentUserRole === ROLE_DISPATCH;
    const canManifest = isAdmin || isDispatch;

    // Manifest UI — visible to ADMIN and DISPATCH only; hidden for REPORTS_ONLY
    formSections.forEach(el => {
        if (canManifest) el.classList.remove('guest-hidden');
        else             el.classList.add('guest-hidden');
    });
    if (previewSection) {
        if (canManifest) previewSection.classList.remove('guest-hidden');
        else             previewSection.classList.add('guest-hidden');
    }
    if (resetBtn) {
        if (canManifest) resetBtn.classList.remove('guest-hidden');
        else             resetBtn.classList.add('guest-hidden');
    }

    // Settings & Users tab — ADMIN only
    if (isAdmin) {
        if (settingsBtn) settingsBtn.classList.remove('guest-hidden');
    } else {
        if (settingsBtn) settingsBtn.classList.add('guest-hidden');
    }

    // Analytics — office roles only; hidden from DRIVER
    const analyticsBtn = document.getElementById('analytics-btn');
    if (analyticsBtn) {
        if (currentUserRole === 'DRIVER') analyticsBtn.classList.add('guest-hidden');
        else analyticsBtn.classList.remove('guest-hidden');
    }
}


// Logout Function
function handleLogout() {
    currentUser = null;
    currentUserId = null;
    currentUserRole = null;
    accessToken = null;
    loginIntent = null;
    clearToken();

    // Hide any open modals
    document.querySelectorAll('.modal').forEach(m => {
        m.classList.add('hidden');
        m.classList.remove('visible');
    });

    // Show landing page
    showLandingPage();
}

/* Export Options & Print Preview Logic */

function showExportOptions() {
    const modal = document.getElementById('export-options-modal');
    if (modal) {
        modal.classList.remove('hidden');
        modal.classList.add('visible');
    }
}

function hideExportOptions() {
    const modal = document.getElementById('export-options-modal');
    if (modal) {
        modal.classList.add('hidden');
        modal.classList.remove('visible');
    }
}

function showReportPrintPreview() {
    hideExportOptions();
    renderReportPrintPreview();
    const modal = document.getElementById('report-preview-modal');
    if (modal) {
        modal.classList.remove('hidden');
        modal.classList.add('visible');
    }
}

function hideReportPreview() {
    const modal = document.getElementById('report-preview-modal');
    if (modal) {
        modal.classList.add('hidden');
        modal.classList.remove('visible');
    }
}

function renderReportPrintPreview() {
    const container = document.getElementById('printable-report-content');
    if (!container) return;

    // Get filter info for header
    const dateFromInput = document.getElementById('report-date-from');
    const dateToInput = document.getElementById('report-date-to');
    const dateFrom = dateFromInput && dateFromInput.value ? formatDate(dateFromInput.value) : 'Any';
    const dateTo = dateToInput && dateToInput.value ? formatDate(dateToInput.value) : 'Any';
    const routeFilter = document.getElementById('report-route-filter').value || 'All Routes';
    const reportTitle = currentReportView === 'outstanding' ? 'Outstanding Orders Report' : 'Dispatch Report';
    const showManifestCol = currentReportView !== 'outstanding';

    const today = new Date().toLocaleString();

    let html = `
        <div class="print-header">
            <div class="print-logo">
                 <img src="logo.png" alt="BRD" style="display:none;" onerror="this.nextElementSibling.style.display='block'">
                 <span style="font-size:24px; font-weight:bold; color:#1e293b;">BRD Distribution</span>
            </div>
            <div class="print-info">
                <h1 style="margin: 0; font-size: 24px; color: #1e293b;">${reportTitle}</h1>
                <p style="margin: 5px 0 0; color: #64748b;">Generated: ${today}</p>
                <p style="margin: 5px 0 0; color: #64748b; font-size: 13px;">
                    Date Range: ${dateFrom} - ${dateTo} | Route: ${routeFilter}
                </p>
            </div>
        </div>
        
        <table class="print-table">
            <thead>
                <tr>
                    <th>Invoice #</th>
                    <th>Order #</th>
                    ${showManifestCol ? '<th>Manifest #</th>' : ''}
                    <th>Truck Reg</th>
                    <th>Customer Name</th>
                    <th>Invoice Date</th>
                    <th>${currentReportView === 'outstanding' ? 'Status' : 'Date Dispatched'}</th>
                    <th>Driver</th>
                    <th>Assistant</th>
                    <th>Checker</th>
                </tr>
            </thead>
            <tbody>
    `;

    if (currentPrintableData && currentPrintableData.length > 0) {
        currentPrintableData.forEach(row => {
            let dispatchedVal = '-';
            if (currentReportView === 'outstanding') {
                dispatchedVal = 'Pending';
            } else if (row.dateDispatched) {
                // Check if it's already formatted or raw date string
                dispatchedVal = row.dateDispatched.includes('/') ? row.dateDispatched : formatDate(row.dateDispatched);
            }

            html += `
                <tr>
                    <td>${row.invoice}</td>
                    <td>${row.orderNumber}</td>
                    ${showManifestCol ? `<td>${row.manifest || '-'}</td>` : ''}
                    <td>${row.truckReg || '-'}</td>
                    <td>${row.customer}</td>
                    <td>${row.invoiceDate}</td>
                    <td>${dispatchedVal}</td>
                    <td>${row.driver}</td>
                    <td>${row.assistant}</td>
                    <td>${row.checker}</td>
                </tr>
            `;
        });
    } else {
        html += `<tr><td colspan="8" style="text-align:center; padding: 20px;">No data available</td></tr>`;
    }

    html += `
            </tbody>
        </table>
        
        <div style="margin-top: 30px; border-top: 1px solid #cbd5e1; padding-top: 10px; display: flex; justify-content: space-between; font-size: 12px; color: #94a3b8;">
            <span>Delivery Manifest System</span>
            <span>Page 1 of 1</span>
        </div>
    `;

    container.innerHTML = html;
}

